services:
  docs:
    image: project_1_local_docs
    container_name: project_1_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./project_1:/app/project_1:z
    ports:
      - '9000:9000'
    command: /start-docs
